django/api/urls.py
from django.urls import path

from rest_framework.routers import SimpleRouter

from .views import PriceListViewSet, CalcListViewSet, CalcSquareListViewSet, PostListViewSet, PricesForCalc

urlpatterns = [
    path('prices-for-calc/', PricesForCalc.as_view(), name="prices_for_calc"),
]

router = SimpleRouter()
# router.register("users", UserViewSet, basename="users")

router.register("posts", PostListViewSet, basename="posts")
router.register("prices", PriceListViewSet, basename="prices")
router.register("calc-square", CalcSquareListViewSet, basename="calc_square")
router.register("calcs", CalcListViewSet, basename='calcs')

urlpatterns += router.urls

django/config/urls.py
import django.views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap

from blog.sitemap import PostSitemap, StaticSitemap
sitemaps = {
    'posts': PostSitemap,
    'static': StaticSitemap,
    }


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path('', include('blog.urls')),
    path('', include('contact.urls')),
    path('', include('price.urls')),
    # path('', include('calc.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('api/v1/', include('api.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# FOR debug_toolbar
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

# handler404 = 'mysite.views.my_custom_page_not_found_view'

django/blog/models.py
from django.db import models
# для организации вложенности
from mptt.models import MPTTModel, TreeForeignKey
from django.utils import timezone
from django.contrib.auth.models import User
from django.shortcuts import reverse
from autoslug import AutoSlugField
from django.template.defaultfilters import slugify  # new
from django_ckeditor_5.fields import CKEditor5Field
from blog.services.utils import validate_file_extension, image_upload_directory, upload_directory_path, convert_image_to_webp


class Category(MPTTModel):
    name = models.CharField(max_length=100, help_text='Название категории')
    slug = models.SlugField(max_length=100, null=False, unique=True)
    parent = TreeForeignKey(
        'self',
        related_name="children",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )

    # def get_absolute_url(self):
    #     return reverse("category_detail", kwargs={'app_name': self.app_name, 'cat_slug': self.category.slug, 'pk': self.pk})

    def __str__(self):
        return self.name

    class MPTTMeta:
        order_insertion_by = ['name']

    def save(self, *args, **kwargs):  # new
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        # '<slug:slug>/<slug:post_slug>'
        return reverse("category_detail", kwargs={'pk': self.pk})


class Tag(models.Model):
    name = models.CharField(max_length=50)
    slug = AutoSlugField(populate_from='name', unique=True)

    def get_absolute_url(self):
        return reverse('tag_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.name




class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    # Begin html meta-data
    keywords = models.CharField(max_length=100, default='', help_text='Meta keywords')
    description = models.CharField(max_length=300, default='', help_text='Meta description')
    meta_title = models.CharField(max_length=300, blank=True, default='', null=True, help_text='Meta title')
    # End html meta-data

    title = models.CharField(max_length=500)

    # TODO check autoslug
    slug = AutoSlugField(populate_from='title', unique=True)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    main_image = models.ImageField(verbose_name='Изображение', upload_to=upload_directory_path, blank=True, null=True)
    # image = models.ImageField(upload_to='articles/%Y/%m/%d/%pk', null=True, blank=True)

    intro = models.TextField(max_length=500, default='',
                             help_text='Little intro text')
    # RichTextField -> for ckeditor
    text = CKEditor5Field(max_length=8000, verbose_name='Основной текст', config_name='extends')

    category = models.ForeignKey(Category, related_name="post",
                                 on_delete=models.SET_NULL,
                                 null=True,
                                 )
    tags = models.ManyToManyField(Tag, verbose_name='Метки', related_name="post")
    pub_at = models.DateTimeField(auto_now_add=True)
    changed = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    is_favorite = models.BooleanField(default=False, help_text='В избранное', )
    views_count = models.BigIntegerField(default=0, null=True, blank=True, verbose_name='Количество просмотров', )

    class Meta:
        ordering = ('-pub_at',)

    app_name = __package__

    def get_absolute_url(self):
        return reverse("post_detail",
                       kwargs={'app_name': self.app_name, 'cat_slug': self.category.slug, 'slug': self.slug})

    def get_tags(self):
        return self.tags.all()

    def get_comments(self):
        return self.comment.all().filter(active=True)

    def get_images(self):
        return self.images.all()

    def get_youtube(self):
        return self.youtube.all()

    def save(self, *args, **kwargs):  # new
        if not self.slug:
            self.slug = slugify(self.title)
        if self.main_image and not self.main_image.name.lower().endswith('.webp'):
            self.main_image = convert_image_to_webp(self.main_image, max_size=800)

        return super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.category} - {self.title}'


# https://youtu.be/EWmsWPaM-Oc?t=266
class Comment(models.Model):
    post = models.ForeignKey(Post, related_name="comment", on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    # website = models.URLField(max_length=200, null=True, blank=True)
    message = models.TextField(max_length=500)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=False)
    # default_avatar = models.ImageField(default='')

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)


class Favorites(models.Model):
    is_favorites = False


class Image(models.Model):
    name = models.CharField(max_length=50, default='', blank=True, null=True)  # alt
    post = models.ForeignKey('Post', related_name='images', on_delete=models.SET_NULL, null=True)
    image = models.ImageField(upload_to=image_upload_directory)
    validators = [validate_file_extension]

    def save(self, *args, **kwargs):
        if self.image and not self.image.name.lower().endswith('.webp'):
            self.image = convert_image_to_webp(self.image)
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.name} - {self.image}'


class VideoYoutube(models.Model):
    name = models.CharField(max_length=250, default='', blank=True, null=True)
    post = models.ForeignKey(Post, related_name='youtube', on_delete=models.SET_NULL, null=True)
    video_frame = models.TextField(max_length=900)

    def __str__(self):
        if self.name:
            return self.name



class Menu(models.Model):
    title = models.CharField(max_length=16)
    url = models.URLField(max_length=200)
    visible = models.BooleanField(default=True)

django/templates/about.html
{% extends 'base.html' %}
{% load about_tags cache%}
{% load static%}
{% block title %}{{ request.site.name }} - {{ main_title }}{% endblock title %}
{% block content %}
{#{% cache 5000 about %}#}
{% include 'hero_over_home.html' %}

{% get_promo %}


<section class="ftco-section">
    	<div class="container">
    		<div class="row justify-content-center">
					<div class="col-md-12">
						<div class="wrapper">
							<div class="row no-gutters mb-5">
								<div class="col-md-7">
                                    {% if messageSent %}
                                        <div id="form-message-success" class="mb-4">
					                        <h5>Ваше сообщение отправлено. Cпасибо, {{ sender }}!</h5>
					      		        </div>
                                    {% else %}
									<div class="contact-wrap w-100 p-md-5 p-4">
										<h3 class="mb-4">Задать вопрос:</h3>
										<div id="form-message-warning" class="mb-4"></div>

                                        <form action="{% url 'contact_us' %}" method="post" class="contact-form">
                                            <div class="row">
                                            {% csrf_token %}
                                            {{ form.as_p }}
                                                <div class="col-md-12">
                                                    <div class="input-list">
                                                        <input type="submit" value="Отправить" class="btn btn-primary">
                                                    </div>
                                                </div>
                                            </div>
                                         </form>
									</div>
                                    {% endif %}
								</div>
								<div class="col-md-5 d-flex align-items-stretch">
									<div id="map">
				          </div>
								</div>
							</div>
							<div class="row">
                                {% for contact in contacts %}
								<div class="col-md-3">
									<div class="dbox w-100 text-center">
				        		<div class="icon d-flex align-items-center justify-content-center">
				        			<span class="fa {{ contact.font_awesome_icon }}"></span>
				        		</div>
				        		<div class="text">

					            <p><a href="{% cycle  'tel://' 'mailto:' %}{{ contact.value }}">{{ contact.value }}</a></p>

					          </div>
				          </div>
								</div>

                                {% endfor %}
{#                                <a href="tel://1234567920"></a>#}
{#                                <a href="mailto:info@yoursite.com">info@yoursite.com</a>#}

							</div>
						</div>
					</div>
				</div>
    	</div>
    </section>

{#{% endcache %}#}
{% endblock %}

django/templates/all_base_tmp.html
{% load humanize %}
{% load static about_tags %}


{% get_promo %}


{#begin HAPPY CLIENTS#}
{% comment %}
    <section class="ftco-section testimony-section bg-primary">
      <div class="container">
        <div class="row justify-content-center mb-5">
          <div class="col-md-7 text-center heading-section heading-section-white ftco-animate">
          	<span class="subheading">Testimonial</span>
            <h2 class="mb-4">Happy Clients</h2>
          </div>
        </div>
        <div class="row ftco-animate">
          <div class="col-md-12">
            <div class="carousel-testimony owl-carousel ftco-owl">
              <div class="item">
                <div class="testimony-wrap py-4">
                	<div class="icon d-flex align-items-center justify-content-center"><span class="fa fa-quote-left"></span></div>
                  <div class="text">
                    <p class="mb-4">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                    <div class="d-flex align-items-center">
                    	<div class="user-img" style="background-image: url(images/person_1.jpg)"></div>
                    	<div class="pl-3">
		                    <p class="name">Roger Scott</p>
		                    <span class="position">Marketing Manager</span>
		                  </div>
	                  </div>
                  </div>
                </div>
              </div>
              <div class="item">
                <div class="testimony-wrap py-4">
                	<div class="icon d-flex align-items-center justify-content-center"><span class="fa fa-quote-left"></span></div>
                  <div class="text">
                    <p class="mb-4">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                    <div class="d-flex align-items-center">
                    	<div class="user-img" style="background-image: url(images/person_2.jpg)"></div>
                    	<div class="pl-3">
		                    <p class="name">Roger Scott</p>
		                    <span class="position">Marketing Manager</span>
		                  </div>
	                  </div>
                  </div>
                </div>
              </div>
              <div class="item">
                <div class="testimony-wrap py-4">
                	<div class="icon d-flex align-items-center justify-content-center"><span class="fa fa-quote-left"></span></div>
                  <div class="text">
                    <p class="mb-4">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                    <div class="d-flex align-items-center">
                    	<div class="user-img" style="background-image: url(images/person_3.jpg)"></div>
                    	<div class="pl-3">
		                    <p class="name">Roger Scott</p>
		                    <span class="position">Marketing Manager</span>
		                  </div>
	                  </div>
                  </div>
                </div>
              </div>
              <div class="item">
                <div class="testimony-wrap py-4">
                	<div class="icon d-flex align-items-center justify-content-center"><span class="fa fa-quote-left"></span></div>
                  <div class="text">
                    <p class="mb-4">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                    <div class="d-flex align-items-center">
                    	<div class="user-img" style="background-image: url(images/person_1.jpg)"></div>
                    	<div class="pl-3">
		                    <p class="name">Roger Scott</p>
		                    <span class="position">Marketing Manager</span>
		                  </div>
	                  </div>
                  </div>
                </div>
              </div>
              <div class="item">
                <div class="testimony-wrap py-4">
                	<div class="icon d-flex align-items-center justify-content-center"><span class="fa fa-quote-left"></span></div>
                  <div class="text">
                    <p class="mb-4">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                    <div class="d-flex align-items-center">
                    	<div class="user-img" style="background-image: url(images/person_2.jpg)"></div>
                    	<div class="pl-3">
		                    <p class="name">Roger Scott</p>
		                    <span class="position">Marketing Manager</span>
		                  </div>
	                  </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    {% endcomment %}
{#end HAPPY CLIENTS#}

{# begin RECENT POSTS #}
    <section class="ftco-section">
      <div class="container">
        <div class="row justify-content-center mb-5 pb-3">
          <div class="col-md-7 heading-section text-center ftco-animate">
             <span class="subheading"> <a href="{% url 'post_list' %}">Наш блог</a></span>
            <h2>Недавние записи</h2>
          </div>
        </div>
        <div class="row d-flex">
{#            {% three_last_posts as  last_posts %}#}
            {% for post in free_latest_posts %}
                {% with post.get_absolute_url as post_url %}
                    <div class="col-md-4 d-flex ftco-animate">
                        <div class="blog-entry align-self-stretch" style="width: 100%;">
                            <a href="{{ post_url }}" class="block-20 rounded" style="background-image: url('{{ post.main_image.url }}');">
                            </a>
                            <div class="text mt-3 text-center">
              	                <div class="meta mb-2">
                                     <h3 class="heading" style="margin-bottom: 8px"><a href="{{ post_url }}">{{ post.title}}</a></h3>
                                        <h6 style="margin-bottom: 0"><a href="{{ post.category.get_absolute_url }}">{{ post.category }}</a></h6>
                                    <div>{{ post.pub_at|naturaltime }}</div>
                                    <div>{{ post.author }}</div>
                                    {% if post.get_comments|length %}<div><span class="icon-chat"></span> {{ post.get_comments|length }}</div>{% endif %}
                                    {% if post.views_count %}<div><span class="icon-eye"></span> {{ post.views_count }}</div>{% endif %}
                                </div>
                              </div>
                            </div>
                          </div>
                {% endwith %}
            {% endfor %}

        </div>
      </div>
    </section>
{# end RECENT POSTS #}

{#begin SIBSCRIBE TO#}
{% comment %}
    <section class="ftco-section ftco-no-pb ftco-no-pt mb-5">
      <div class="container">
      	<div class="row">
	      	<div class="col-md-12">
	      		<div class="bg-primary w-100 rounded px-md-0 px-4">
			        <div class="row d-flex justify-content-center">
			        	<div class="col-lg-8 py-4">
			        		<div class="row">
					          <div class="col-md-6 d-flex align-items-center">
					            <h2 class="mb-0" style="color:white; font-size: 24px;">Subcribe to our Newsletter</h2>
					          </div>
					          <div class="col-md-6 d-flex align-items-center">
					            <form action="#" class="subscribe-form">
					              <div class="form-group d-flex">
					                <input type="text" class="form-control" placeholder="Enter email address">
					                <input type="submit" value="Subscribe" class="submit px-3">
					              </div>
					            </form>
					          </div>
				          </div>
			          </div>
			        </div>
			      </div>
			    </div>
			  </div>
      </div>
    </section>
   {% endcomment %}
{#end SIBSCRIBE TO#}

django/templates/base.html
<!DOCTYPE html>
<html lang="ru" prefix="og: https://ogp.me/ns#>
{% load blog_tags about_tags static %}
  <head>

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-KHCBR73MDM"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-KHCBR73MDM');
</script>

    <title>{% block title %}{% endblock title %}</title>

    <meta charset="utf-8">
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="keywords" content="{% block keywords %}{% endblock %}">
    <meta name="author" content="Aleksei Mashtakov">
  {#https://sky.pro/media/razmeshhenie-izobrazheniya-dlya-predprosmotra-ssylki-v-whatsapp/#}
  {% block add_to_head %}

  {% endblock %}
{#{% block add_to_head %}#}
{#{% recaptcha_init %}#}
{#  {% recaptcha_ready action_name='homepage' %}#}
{#{% endblock %}#}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
{#  load extended js#}
      <script type="text/javascript">{% block extendeed_js %}{% endblock %}</script>
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900&display=swap" rel="stylesheet">

{#    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">#}

{#    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.1/css/fontawesome.min.css">#}
{#    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@4.7.0/css/fontawesome.min.css">#}
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">

    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'css/nstyle.css' %}">
    <link rel="icon" href="{% static 'favicon.ico'%}">
  
  </head>
  <body>

{#  LOAD INCLUSION TAGS FOR ALL PAGES#}
{% tag_list as tags %}
{% get_social_links as social %}
{% not_empty_cats as categories %}
{#  end LOAD INCLUDED TAGS FOR ALL PAGES#}
    {% include 'logo.html' %}
    <!-- BEGIN nav -->
{% include 'nav.html' %}
    <!-- END nav -->


    {% block content %}


    {% endblock %}


{#  begin  footer#}
{% include 'footer.html' %}
{#end footer#}

  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'js/scrollax.min.js' %}"></script>
{#  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>#}
{#  <script src="{% static 'js/google-map.js' %}"></script>#}
  <script src="{% static 'js/main.js' %}"></script>

  </body>
</html>


{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{##}
{#    <meta charset="UTF-8">#}
{#    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">#}
{#    <meta name="keywords" content="{% block keywords %} {% endblock %}"/>#}
{#    <meta name="description" content="{% block description %} {% endblock %}"/>#}
{#    <title>{% block title %}{% endblock title %}</title>#}
{#</head>#}
{#<body>#}
{#{% block content %}{% endblock %}#}
{##}
{##}
{#</body>#}
{#</html>#}

django/templates/footer.html
{% load cache %}


<footer class="footer">
			<div class="container-fluid px-lg-5">
				<div class="row">

{#                {% cache 5000 footer %}#}
					<div class="col-md-9 py-5">
						<div class="row">
							<div class="col-md-4 mb-md-0 mb-4">
								<h2 class="footer-heading">_____</h2>
								<p>Вся информация, представленная на сайте,
                                    носит исключительно информационный характер
                                    и ни при каких условиях не является публичной офертой.</p>
								<ul class="ftco-footer-social p-0">

                                    {% for soc in social %}
		              <li class="ftco-animate"><a href="{{ soc.link }}" data-toggle="tooltip" data-placement="top" title="{{ soc.name }}"><span class="ion-logo-{{ soc.font_awesome_code }}"></span></a></li>
		                            {% endfor %}
                                </ul>
							</div>
							<div class="col-md-8">
								<div class="row justify-content-center">
									<div class="col-md-12 col-lg-10">
										<div class="row">
											<div class="col-md-4 mb-md-0 mb-4">
												<h2 class="footer-heading"><a class="footer-heading" href="{% url 'category_list' %}" class="nav-link">Категории</a></h2>
                                                <ul class="list-unstyled">
                                                    {% for cat in categories %}
                                                    <li><a href="{{cat.get_absolute_url}}" class="py-1 d-block">{{ cat.name }}</a></li>
                                                    {% endfor %}
                                                </ul>
											</div>
											<div class="col-md-4 mb-md-0 mb-4">
												<h2 class="footer-heading">Меню</h2>
												<ul class="list-unstyled">
						              <li><a href="{% url 'home' %}" class="py-1 d-block">Главная</a></li>
						              <li><a href="{% url 'about' %}" class="py-1 d-block">О нас</a></li>
						              <li><a href="{% url 'favorites_list' %}" class="py-1 d-block">Наши работы</a></li>
						              <li><a href="{% url 'price' %}" class="py-1 d-block">Цены</a></li>
						              <li><a href="{% url 'post_list' %}" class="py-1 d-block">Блог</a></li>
{#						              <li><a href="{% url 'home/calc'%}" class="py-1 d-block">Калькулятор</a></li>#}
						            </ul>
											</div>
											<div class="col-md-4 mb-md-0 mb-4">
												<h2 class="footer-heading">Метки</h2>
												<ul class="list-unstyled">
{#                                                    {% tag_list as tags %}#}
                                                    {% for tag in tags %}
                                                   <li> <a href="{{ tag.get_absolute_url }}" class="py-1 d-block">{{ tag.name }}</a></li>
                                            {% endfor %}
						                    </ul>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="row mt-md-5">
							<div class="col-md-12">
								<div class="copyright">
                                    <p><a href="{% url 'home' %}">&copy;<script>document.write(new Date().getFullYear());</script> remont199.com</a></p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
					  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="ion-ios-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib.com</a>
					  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                </div>
							</div>
						</div>
					</div>
{#                {% endcache %}#}

					<div class="col-md-3 py-md-5 py-4 aside-stretch-right pl-lg-5">
                          <ul>
                           {% if user.is_authenticated %}
                             <li>User: {{ user.get_username }}</li>
                             <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
                             <li><a href="{% url 'post_create'%}">Add post</a></li>
                           {% else %}
                             <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
                           {% endif %}
                          </ul>
					</div>


				</div>
			</div>
		</footer>

django/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container">

	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="fa fa-bars"></span> Меню
	      </button>
            <form action="{% url 'search_result' %}" class="searchform order-lg-last">
          <div class="form-group d-flex">
            <input type="text" class="form-control pl-3" name='q' placeholder="Поиск">
            <button type="submit" placeholder="" class="form-control search"><span class="fa fa-search"></span></button>
          </div>
        </form>

	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if nbar == 'home' %}active{% endif %}"><a href="{% url 'home' %}" class="nav-link">ГЛАВНАЯ</a></li>
                <li class="nav-item {% if nbar == 'about' %}active{% endif %}"><a href="{% url 'about' %}" class="nav-link">О НАС</a></li>
                <li class="nav-item"><a href="{% url 'favorites_list' %}" class="nav-link">РАБОТЫ</a></li>
                <li class="nav-item"><a href="{% url 'price' %}" class="nav-link">ЦЕНЫ</a></li>
                <li class="nav-item {% if nbar == 'blog' %}active{% endif %}"><a href="{% url 'post_list' %}" class="nav-link">БЛОГ</a></li>
{#	            <li class="nav-item {% if nbar == 'calc' %}active{% endif %}"><a href="{% url 'calc' %}" class="nav-link">КАЛЬКУЛЯТОР</a></li>#}
	            <li class="nav-item"><a href="https://remont199.com/calc/" class="nav-link">КАЛЬКУЛЯТОР</a></li>
	        </ul>
	      </div>
	    </div>
	  </nav>